Fix #1226 listObjectsV2 breaks bucket path to host
async-aws/aws pull request #1229
Opened 2022-04-29 10:29 UTC by Redominus

S3 listObjectsV2 breaks bucket path to host

2022-04-29 10:44 UTC, Redominus commented
I would really appreciate some help with PHPStan analysis as I did not change any method signature

2022-04-29 11:19 UTC, jderusse requested changes
You can not change this file.  This file is automatically generated and the URL is part of the AWS spec. 

You have 2 options:
- change the generator (that dump the file) to detect URI containing query string and generating the patch you submitted.
- change the S3Client getEndpoint method to ignore the querystring from the URI when guessing the bucket.

The first option is closer to your patch, but I have some concern:
- the $query property is used in many places, including generating signatures. I fear that changing this behavior might generate authentication issue
- Some S3 operations use queryString that looks like `"/{Bucket}?tagging"`, but the AsyncAws core component expects a key/value to generate URL containing `key=value`. If you change the Generator to move the querystring part to the `$query` parameter, you first need to make the `sync/core` component compatible with options without value `$query['tagging'] = null` must generate `?tagging` instead of `?tagging=`

That's why I believe the solution 2 would be better.

Tell me if you need help

2022-04-29 12:55 UTC, Redominus commented
Hope this is fine. It does not changes the query.

2022-04-30 09:00 UTC, jderusse commented on src/Service/S3/src/S3Client.php
> +        $uriWithOutBucket = preg_replace('~^[^?]+~', '', $uriParts[1] ?? '') . ($uriParts[2] ?? '');
no need to use regexp
```suggestion
        $uriWithOutBucket = substr($uriParts[1] ?? '', strlen($bucket)) . ($uriParts[2] ?? '');
```

2022-04-30 18:41 UTC, Redominus commented
It had a bit of influence from being a regex golfer :rofl:

2022-04-30 18:58 UTC, jderusse approved these changes

2022-05-01 19:11 UTC, merged