Athena client :  update documentations
async-aws/aws pull request #1397
Opened 2023-05-03 13:30 UTC by karamokobaD

Update Athena getQueryResults exemple

2023-05-03 14:38 UTC, jderusse commented on src/Core/CHANGELOG.md
> +- Athena Client: Documentation updates.
Should be removed, the documentation is not part of the component

(same for other readme files)

2023-05-04 10:28 UTC, GrahamCampbell requested changes

2023-05-04 10:28 UTC, GrahamCampbell commented on docs/clients/athena.md
> +                                static function ($data) {
This indentation is too far over. We should be only 8 spaces in in total.

2023-05-09 05:28 UTC, jderusse approved these changes

2023-05-09 05:28 UTC, merged

2023-05-09 05:28 UTC, jderusse commented
thank you @karamokobaD