Prepare next releases
async-aws/aws pull request #1435
Opened 2023-06-12 08:28 UTC by jderusse

component | version
----------|--------
core | 1.19
appsync | 1.1.0
athena | 1.0.0
cloud-formation | 1.4.0
cloud-watch-log | 1.6.0
comprehend | 1.0.0
dynamodb | 1.4.0
ecr | 1.4.0
elasti-cache | 1.1.0
event-bridge | 1.4.1
iot | 1.0.0
iot-data | 1.0.0
kinesis | 2.0.0
kms | 1.0.0
lambda | 1.9.0
rekognition | 1.0.0
route53 | 1.1.0
s3 | 1.14.0
secrets-manager | 1.0.0
sqs | 1.8.0
ssm | 1.4.0
step-functions | 1.1.0
timestream-write | 1.1.0
symfony-bundle | 1.11.0
monolog-cloud-watch | 1.0.1

2023-06-12 08:30 UTC, jderusse commented on src/Service/Kinesis/CHANGELOG.md
> +- BC BREAK: `listStreams` now yield over stream names AND descriptions
Am I right here? 

For reference, this has been introduced by AWS in https://github.com/async-aws/kinesis/commit/0841292426cadbe269a54f102b750935f77219da

2023-06-12 08:54 UTC, GrahamCampbell requested changes
async-aws/timestream-query 1.0.0 is missing from this list

2023-06-12 10:47 UTC, stof commented
it would be great to merge #1417 first too, so that it could be released as well.

2023-06-12 10:48 UTC, stof commented on src/Core/CHANGELOG.md
> +## 1.19
should be `1.19.0` for consistency.

2023-06-12 10:48 UTC, stof commented on src/Core/CHANGELOG.md
>  - Support for using endpoint discovery with parameters passed in the query string or the path
should `Added` be added here as well ?

2023-06-12 10:48 UTC, stof commented on src/Core/CHANGELOG.md
> -- Support for Athena
this was actually consistent with many previous versions.

2023-06-12 10:50 UTC, stof commented
@jderusse as our `BC checks` CI jobs are currently broken, maybe they should be fixed before the release ? See the discussions on Slack about that topic.

2023-06-13 07:25 UTC, jderusse commented
> @jderusse should MediaConvert start as 0.1.0 or should it go directly to 1.0.0 ?

We usually start with a `0.1` version to allow the contributor to test it and see if they need more operations. 
If you believe this is not necessary we can skip this and directly start at `1.0`. Just tell me what's your preference.

2023-06-13 10:08 UTC, jderusse commented
BC check still fails.. I've no clue how this thing work / should work
https://github.com/async-aws/comprehend/actions/runs/5253712955/jobs/9491391212

Any idea?

2023-06-13 10:12 UTC, GrahamCampbell commented
It is because you need to add `fetch-depth: 0` when checking out as per the README: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches.

2023-06-20 19:17 UTC, merged