Upgrade psalm
async-aws/aws pull request #1462
Opened 2023-06-23 08:24 UTC by stof

2023-06-23 09:08 UTC, GrahamCampbell requested changes

2023-06-23 09:08 UTC, GrahamCampbell commented on .github/workflows/static.yml
> +        uses: docker://ghcr.io/psalm/psalm-github-actions:5.11.0
can we install the psalm phar, similar to the way we do phpstan?

```
"psalm/phar": "5.11.0"
```

2023-06-23 09:15 UTC, jderusse reviewed
Is there a reason for not using composer like we did for phpstan and BC-break-checker?

2023-06-23 09:23 UTC, stof commented
@jderusse I kept it closer to the way it was done right now. But I'm strongly in favor of using composer

2023-06-23 09:27 UTC, jderusse commented
> @jderusse I kept it closer to the way it was done right now. But I'm strongly in favor of using composer

I'm also in favor of migrating to composer: Docker images are not always maintained, and also prevent contributor from running tools on their local environments

2023-06-23 09:41 UTC, stof commented
Well, running Psalm locally is still a pain because it requires installing dependencies with an old PHP version as target (due to the fact that Psalm defaults to analyzing the code with the lowest bound of the composer requirement for PHP but also insists that the code scanned in the vendor folder can be analyzed with this PHP version)

2023-06-23 10:22 UTC, stof commented
I have no idea why the CI fails. Running the same Psalm version locally does not report the error.

2023-06-23 11:19 UTC, GrahamCampbell commented
Possibly a bad local psalm cache. psalm is pretty bad at getting itself in a situation with an incorrect cache if things are moving around while it is running.

2023-06-23 11:35 UTC, stof commented
I'm getting this difference even with the psalm cache deleted and the `--no-cache` option

2023-06-23 12:43 UTC, GrahamCampbell commented
Hmm. 🤷

2023-06-26 09:28 UTC, stof commented
I still don't know why my local setup was not detecting this error. But as it is a legitimate one, I fixed it in the PR.

2023-06-26 09:53 UTC, jderusse approved these changes

2023-06-26 09:53 UTC, merged