Use quoted literal in phpdoc when psalm needs them
async-aws/aws pull request #1518
Opened 2023-07-10 10:13 UTC by stof

See https://github.com/vimeo/psalm/issues/10008

Psalm treats array key shapes that match their keywords as keywords and then makes them lowercase, breaking the array shape (as array keys are case sensitive).

This updates the code generator to generate string literals for the keys for this case, to ensure compatibility with both phpstan and psalm.

2023-07-10 10:16 UTC, GrahamCampbell approved these changes

2023-07-10 10:30 UTC, jderusse requested changes
I'm against messing our code base because of buggy tools.

2023-07-10 10:46 UTC, GrahamCampbell commented
I don't think this is a tooling bug - this is happening because bool and null are primitive literals.

2023-07-10 10:46 UTC, GrahamCampbell commented
We should not expect `'foo'` to be treated as a literal in a type, but then not `bool`. We are also very used to `null` being treated as a literal.

2023-07-10 10:48 UTC, GrahamCampbell commented
The fact that null cannot be in an array key is a semantic rule, and we cannot expect the syntax to encode that.

2023-07-10 11:15 UTC, jderusse commented
> this is happening because bool and null are primitive literals.


the dockbloc syntax `array{x: Y}` means `literally "x"`.
If I wanted to express a type of value for the key, I would have used `array<typeOfX, Y>` (ie. `array<string, Y>` or `array<bool, Y>`.

PHP does not allow `type` as an array key. `$array[bool];` [is syntaxly incorrect in PHP.](https://3v4l.org/HYl7M) 

Therefore the docbloc `array{bool: type}` treated in something else than `$array["bool"]` is meaningless.

2023-07-10 11:58 UTC, stof commented
Well, regarding `@region`, PHPStorm was already failing the parsing without quotes around it (but in a less abrupt way). And they recognized that the issue with shape keys starting with `@` was an issue with their phpdoc parser.

However, I'm fine with waiting for the resolution on the Psalm side.

2023-08-09 08:18 UTC, GrahamCampbell approved these changes
I'd be really helpful to have this merged, even though this is not really an issue on our side, as such. It is not uncommon for projects to work around bugs in 3rd party code. ;)

2023-08-09 09:02 UTC, stof commented
As one of the benefits of async-aws over the official SDK is type safety, it would be great to have this merged to avoid Psalm users getting SA errors on valid code hinting them to make their code invalid. The maintenance cost should be minimal as the affected types are generated ones. And this only takes a small amount of code in the TypeGenerator.

I added a TODO comment referencing the Psalm issue so that we know what this code is about and we could remove it in the future if Psalm fixes its issue.

2023-09-03 12:22 UTC, GrahamCampbell commented
Any chance we can get this merged? This causes me problems most days.

2023-09-03 12:45 UTC, jderusse approved these changes
Even if I'm really upset by these buggies SAT (that asks everyone to add workarounds to make them work), I hear your pain.
Let's go ahead and move it forward. 

@stof would you mind to rebase this PR?

2023-09-04 06:58 UTC, stof commented
@jderusse rebase is done

2023-09-04 08:51 UTC, merged