Event bridge - Fix SSL handshake for more requests use resolve method
async-aws/aws pull request #1655
Opened 2024-01-22 21:23 UTC by lukasojd

2024-01-22 22:12 UTC, GrahamCampbell commented
Interesting. Is this still happening if you set the max connections to 1 on the curl http client, without using this change?

2024-01-22 22:15 UTC, GrahamCampbell requested changes

2024-01-22 22:15 UTC, GrahamCampbell commented on src/Core/src/Response.php
>                  $this->httpResponse->getStatusCode();
This line is no longer needed, due to the line you added after.

2024-01-22 22:24 UTC, lukasojd commented
Fix please test cc @lukasojd

2024-01-22 22:33 UTC, lukasojd commented
> Interesting. Is this still happening if you set the max connections to 1 on the curl http client, without using this change?

I have conducted tests using the default Symfony client (Symfony\Component\HttpClient\CurlHttpClient), specifically setting the maximum number of host connections to 1. Here's the relevant code snippet:

```
$client = new CurlHttpClient(maxHostConnections: 1);
$this->client = new EventBridgeClient(
    configuration: [
        'accessKeyId' => $this->accessKeyId,
        'accessKeySecret' => $this->accessKeySecret,
        'region' => $this->region,
    ],
    httpClient: $client,
    logger: $this->logger,
);
```

Despite this adjustment, the issue persists. The configuration was set up as per the example above, ensuring that only one connection per host is maintained at any time. However, it seems that this configuration change alone does not resolve the problem.

Additionally, I have also monitored the network traffic and confirmed that the issue indeed involves the closing of connections when the response is not fully retrieved. This results in repeated packets associated with connection re-establishment and the SSL handshake process. It's evident from the network analysis that each new request initiates a fresh connection cycle, including the SSL handshake, which aligns with the observed performance issue.

2024-01-22 22:40 UTC, jderusse commented
@nicolas-grekas does it rings a bell?

We don't consume the entire response to save few IO. But it looks like the side effect is,  the response is not free for curl, and it don't reuse it.

How can we tell SymfonyClient to stop streaming the response, but keep the connection alive?

2024-01-23 10:26 UTC, lukasojd commented
@GrahamCampbell @jderusse  @nicolas-grekas I've continued troubleshooting the issue and discovered that the problem is related to specific versions of curl. It appears that versions prior to 7.87.0 are affected, while the issue has been resolved starting from curl 7.87.0. Considering this, I believe it may not be necessary to insist on this merge request. The resolution might simply involve updating to a newer version of curl. I leave the decision up to you on how to proceed further.

2024-01-23 10:33 UTC, nicolas-grekas commented
Thanks for digging!
Given [7.87.0 is one year old](https://curl.se/docs/vuln-7.87.0.html), it might be fine doing nothing indeed.
Unless we're sure that fetching all the body won't generate needless network traffic (because responses are small) in which case why not.

2024-01-23 11:33 UTC, GrahamCampbell commented
Using the amphp http client may be a suitable work-around for you?

2024-01-28 20:45 UTC, closed without merging