Add documentation about declaring multiple clients
async-aws/aws pull request #910
Opened 2020-12-29 17:33 UTC by jderusse

Fixes #908 ping @derrabus

2020-12-29 18:07 UTC, derrabus approved these changes

2020-12-30 21:46 UTC, Nyholm commented on docs/integration/symfony-bundle.md
> -| `async_aws.client.sts`     | AsyncAws\Core\Sts\StsClient
These should not be removed. 

> This example assume you have installed core, ses, sqs and s3

2020-12-30 21:46 UTC, Nyholm requested changes
Thank you

2020-12-30 21:58 UTC, jderusse commented on docs/integration/symfony-bundle.md
> -| `async_aws.client.sts`     | AsyncAws\Core\Sts\StsClient
Oh right. I forgot about this behavior.

2020-12-30 22:59 UTC, Nyholm approved these changes

2020-12-30 22:59 UTC, merged

2020-12-30 22:59 UTC, Nyholm commented
Thank you